### ISSUE TITLE
Lazy loading on scrolling div (iPad)

### ISSUE THREAD

**Issue by sergiom88** [ressio/lazy-load-xt#24]
Hello,
I'm having some problems trying to make a scrollable div lazy load the images inside. It works perfectly on the desktop browser but when on mobile safari when I scroll (scrolls with momentum) the images are not shown until the scrolling stops completely. This also means that the onshow function is not executed until the scrolling stops. BTW I'm using both spinner and fade effect.

This is how I'm initialising the plugin.

```javascript
$.extend($.lazyLoadXT, {
       				autoInit:false,
       				edgeY:0,
                                scrollContainer: "#searchResultsList",
       				onshow: function(){
       					$(this).addClass('lazy-hidden lazy-hidden-spinner lazy-force-spinner');
				}, 
       				onload: function(){
       					//remove the forced spinner first to allow fade
       					$(this).removeClass("lazy-force-spinner");
       					$(this).removeClass("lazy-hidden-spinner");
       					$(this).removeClass("lazy-hidden");
       					$(this).addClass("lazy-loaded");
           			}
       		});
```
Later on the code once an item has been added to the DOM I do the following.

```javascript
var toAppend = $( itemHTML );
resultsContainer.append(toAppend);
toAppend.find("img[data-src]").lazyLoadXT();
```

Related CSS is below. I am using -webkit-transform: translate3d(0,0,0); in the scrollable div to use hardware acceleration but that doesn't help. I also tried adding it to the images but still the same.

```css
.lazy-hidden-spinner
{
	background:url('../images/lazy_loading.gif') no-repeat 50% 50%;
		
}

.lazy-force-spinner
{
	height: 100%;
	width: 100%;
	opacity: 1 !important;
}

#searchResultsList
{
	padding:0px 62px;
	height: 100%;   
    overflow:scroll;  
    -webkit-overflow-scrolling: touch;      
    -webkit-transform: translate3d(0,0,0);
}
```
I'm sure there is something I'm missing but cant figure out what.

Thanks for and awesome plugin.

Sergio

#### Update
I noticed that the problem really is because the scroll event is not triggered on safari mobile when "momentum scrolling".
